### ISSUE TITLE
Harry Roberts's name

### ISSUE THREAD

**Issue by alexrussell** [chantastic/practical-bem#2]
> These examples use the most popular [`--` dialect](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) by Harry Robert's.

Should be:

> These examples use the most popular [`--` dialect ](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/)by Harry Roberts.

**Comment by chantastic** [comment]
Thanks!
